
List questions_list = [
  {
    'question': 'What planet do we live on?',
    'option 1': 'Earth',
    'option 2': 'Mars',
    'option 3': 'Jupiter',
    'option 4': 'Uranus',
  },
  {
    'question': 'What is 1+1?',
    'option 1': '1',
    'option 2': '2',
    'option 3': '3',
    'option 4': '4',
  },
  {
    'question': 'What is the Capital of India?',
    'option 1': 'Delhi',
    'option 2': 'Jaipur',
    'option 3': 'Mumbai',
    'option 4': 'Pune',
  },
  {
    'question': 'Who won the 2022 FIFA WC?',
    'option 1': 'France',
    'option 2': 'Argentina',
    'option 3': 'India',
    'option 4': 'Portugal',
  },
  {
    'question': 'What year did COVID-19 originated',
    'option 1': '2022',
    'option 2': '2020',
    'option 3': '2019',
    'option 4': '2018',
  },
  {
    'question': 'What is H20?',
    'option 1': 'Mercury',
    'option 2': 'Water',
    'option 3': 'Wood',
    'option 4': 'Alcohol',
  },
  {
    'question': 'Which country has highest number of billionaires?',
    'option 1': 'USA',
    'option 2': 'India',
    'option 3': 'UK',
    'option 4': 'Italy',
  },
  {
    'question': 'Who is bought Twitter in 2022?',
    'option 1': 'Jeff Bezos',
    'option 2': 'Bill gates',
    'option 3': 'Elon Musk',
    'option 4': 'Kevin Heart',
  },
  {
    'question': 'Who won the Rap Album of the year in 2022',
    'option 1': 'the Weekend',
    'option 2': '21 Savage',
    'option 3': 'Migos',
    'option 4': 'Kendrick',
  },
  {
    'question': 'What is the powerhouse of the cell?',
    'option 1': 'Mitochondria',
    'option 2': 'Nucleus',
    'option 3': 'Chromosomes',
    'option 4': 'Proteins',
  },
];
